export default {
    SHORT_RUN_WIN: "5 yard gain. Continue to RSP.",
    SHORT_RUN_TIE: "No Gain",
    SHORT_RUN_LOSS: "Defense rolls.\n1-4: No loss\n5-6: 5 yard loss",
    LONG_RUN_WIN: "5 yards times roll of die. 1 = fumble.",
    LONG_RUN_TIE: "No Gain",
    LONG_RUN_LOSS: "Defense rolls.\n1-5: 5 yard loss\n6: 10 yard loss",
    SHORT_PASS_WIN: "10 yard gain. Continue to RSP.",
    SHORT_PASS_TIE: "No Gain",
    SHORT_PASS_LOSS: "5 yard loss - or - defense rolls die,\n1-5: incomplete pass\n6: interception",
    LONG_PASS_WIN: "10 yards plus the roll of the die",
    LONG_PASS_TIE: "No Gain",
    LONG_PASS_LOSS: "10 yard loss - or - defense rolls die,\n1-4: incomplete pass\n5-6: interception",
    BOMB_WIN: "35 yard gain minimum. Roll up to 3 dice, one at a time; for completion total must be odd.",
    BOMB_TIE: "No Gain",
    BOMB_LOSS: "15 yard loss - or - defense rolls die,\n1,3,5: incomplete pass\n2,4,6: interception",

    TURNOVER_RESULT_DOWNS: "Turnover on downs",
    TURNOVER_RESULT_FUMBLE: "Fumble recovered by defense. Turnover!",
    TURNOVER_RESULT_PICK: "Interception!",
    OUT_OF_BOUNDS_PASS: "Throw out of bounds. Incomplete.",
    OUT_OF_BOUNDS_KICK: "Kick out of bounds.",
    INCOMPLETE_PASS: "Incomplete",
    TOUCHBACK: "Touchback",
    ONSIDE_KICK: "Onside kick!",
    SCORE_TOUCHDOWN: "Touchdown!",
    SCORE_FIELD_GOAL: "Field Goal!",

    SCORE_PAT_1: "Extra point is good!",
    SCORE_PAT_2: "Two point conversion!",
    SCORE_SAFETY: "Safety!",
};
